### ISSUE TITLE
The compiler is unable to check that this switch is exhaustive in reasonable time

### ISSUE THREAD

**Issue by achirkof** [thii/FontAwesome.swift#217]
Hi! Got an issue trying to build app "The compiler is unable to check that this switch is exhaustive in reasonable time"

<img width="1371" alt="Screenshot 2019-07-09 at 16 09 30" src="https://user-images.githubusercontent.com/1292136/60890677-78492680-a264-11e9-88fb-19de247d11cc.png">

Probably need to add default value.

It works several days ago. Looks like updating fonts might be a cause of issue.

**Comment by thii** [comment]
Thanks for reporting this. Would you mind to open a PR to fix it?

**Comment by LukasHromadnik** [comment]
Can you please provide us with some information? Like hardware specs, Xcode version, library version and version of the Cocoapods?

I've just tried my test app on my very old Macbook 2012 and I'm not getting this error during the build nor the archivation.

**Comment by achirkof** [comment]
My laptop is: 
MacBook Pro (Retina, 15-inch, Mid 2014)
Processor 2,5 GHz Intel Core i7
Memory 16 GB 1600 MHz DDR3
Xcode 11 beta 3 (11M362v)

I think it's specific for Xcode 11 error.

**Comment by benben28405678** [comment]
I compiled the code in `Enum.swift` and ran into no issues. Not sure if you fixed the issue in the weeks since the last comment, but it seems to me that everything runs fine with the `switch` statement.

Looks like it's an Xcode 11 issue.

-Ben

Model Name: MacBook Pro (2017)
Model Identifier: MacBookPro14,2
Processor Name: Intel Core i5
Xcode Version 10.2.1 (10E1001), Swift 5

**Comment by robertcrabtree** [comment]
I have the same issue with Xcode Version 11.0 beta 4. No problems with Xcode 10.3

**Comment by thii** [comment]
Could you file a bug report to Apple?

**Comment by danielrobleM** [comment]
I have the same issue with Xcode Version 11.0 beta 3.

**Comment by ykphuah** [comment]
Same issue with Xcode 11 beta 5 as well.

**Comment by ykphuah** [comment]
Created a pull request 
https://github.com/thii/FontAwesome.swift/pull/222

**Comment by Tulleb** [comment]
> Could you file a bug report to Apple?

I don't think this is a bug. It looks like Xcode 11 is just being more restrictive on the enum switch to be able to compile faster.

**Comment by ruizmarc** [comment]
Same issue with Xcode 11 beta 6 as well. I'm with @Tulleb , it seems they are getting more restrictive.

**Comment by umutalparslan** [comment]
I'm having the same problem. I'm using Xcode 11 beta 6.

**Comment by ruizmarc** [comment]
This issue has been fixed with https://github.com/thii/FontAwesome.swift/pull/222

**Comment by gezamiklo** [comment]
The issue still persists. I understand that the swith is exhaustive, but cannot alter the compiler. Maybe in the final version it will compile. Who knows?
