### ISSUE TITLE
Cocoapods Says latest version 5.14.0

### ISSUE THREAD

**Issue by phoney** [thii/FontAwesome.swift#263]
When I run pod outdated I get

```
The following pod updates are available:
- FontAwesome.swift 1.9.0 -> 1.9.0 (latest version 5.14.0)
```

Apparently there is a tag '5.14.0' AFAICT it's not on any branch. 
If I run:
```git branch -a --contains 8e8912c```
the result is empty.

What I guess happened is that a branch was made with a commit 
```
$ git checkout 5.14.0
~/develop/Samples/FontAwesome.swift  [(5.14.0)] $ git lol
* 8e8912c (HEAD, tag: 5.14.0) Bump FontAwesome version to 5.14.0
* 2684b5b (tag: 1.9.0) Bump version to 1.9.0
```

Then the branch was deleted. git doesn't delete tags even though the branch it's on has been deleted. The tag is keeping that branch alive. I assume this tag was never meant to be kept around.
To fix this the tag needs to be deleted.

```git tag -d 5.14.0```

This seems also like a Cocoapods issue. I don't see why it should say that a tag on a dead branch is the most recent version when it's not on master and conflicts with what's in the podspec. ```pod update``` doesn't update to the 5.14.0 tag.

**Comment by MatrixSenpai** [comment]
wild. thanks for letting me know. I just deleted the tag, should fix the issue. close if true, thanks

**Comment by phoney** [comment]
I can see that the tag is gone (it was previously visible in the GitHub tags menu). But I still get the same output from ```pod outdated```. Maybe it will be fixed next time a new version is released to Cocoapods, but I'm really not sure.

I filed an issue with the Cocoapods project

https://github.com/CocoaPods/CocoaPods/issues/9988

**Comment by phoney** [comment]
@MatrixSenpai Can you review and maybe comment on the issue in the Cocoapods project listed upthread? A dev there points out that the page below shows that the latest version is 5.14.0. Not sure how that happened or how to fix it.

https://cocoapods.org/pods/FontAwesome.swift

**Comment by MatrixSenpai** [comment]
I must have pushed it to the trunk and forgot about it. I'll fix it tonight

**Comment by keeshux** [comment]
Deleting the tag is not enough, you should deprecate/remove the pod in trunk. FYI pod installation is completely broken today.

**Comment by MatrixSenpai** [comment]
v5.14.0 has been removed from the pod trunk. Also, @keeshux can you open a new issue with the problems you're experiencing? Please include the version number

**Comment by keeshux** [comment]
> v5.14.0 has been removed from the pod trunk. Also, @keeshux can you open a new issue with the problems you're experiencing? Please include the version number

No new issue. I meant that `pod 'FontAwesome.swift'` could not work until the broken version was removed. Having removed the pod on your end and updated the pod repo on mine, the issue has been solved. Thanks!
